#pragma once

/*
Represents a fixed command. Their actions are binary (they either
are executed or not), and do not require any extra parameters.
*/
enum eFixedCommand
{
    // In game
    COMMAND_ABILITY_ROCKET,
    COMMAND_ABILITY_SPIKES,
    COMMAND_ABILITY_TRAIL_ACTIVATE,
    COMMAND_ABILITY_TRAIL_DEACTIVATE,
    COMMAND_CAMERA_BACK,
    COMMAND_CAMERA_FRONT,
    COMMAND_DASH_BACK,
    COMMAND_DASH_FORWARD,
    COMMAND_DASH_LEFT,
    COMMAND_DASH_RIGHT,
    COMMAND_MENU_BACK,
    COMMAND_MENU_PAUSE_TOGGLE,
    COMMAND_INVALID_FIXED,
    COMMAND_MOVE_FORWARD,
    COMMAND_MOVE_RIGHT,
    COMMAND_MOVE_LEFT,
    COMMAND_MOVE_BACK,
    COMMAND_TURN_RIGHT,
    COMMAND_TURN_LEFT,
    COMMAND_HONK_UP,
    COMMAND_HONK_RIGHT,
    COMMAND_HONK_DOWN,
    COMMAND_HONK_LEFT,
    // PromptMenu
    COMMAND_PROMPT_UP,
    COMMAND_PROMPT_LEFT,
    COMMAND_PROMPT_DOWN,
    COMMAND_PROMPT_RIGHT,
    COMMAND_PROMPT_CURSOR_RELEASE,
    COMMAND_PROMPT_SELECT,
    COMMAND_PROMPT_SELECT_2,
    COMMAND_PROMPT_SELECT_3,
    COMMAND_PROMPT_SELECT_4,
    COMMAND_PROMPT_SELECT_5,
    COMMAND_PROMPT_SELECT_6,
    COMMAND_PROMPT_SELECT_7,
    COMMAND_PROMPT_BACK,
    COMMAND_PROMPT_NEXT_MENU,

    COMMAND_MENU_START, // Currently does nothing, may remove or change name in future

    COMMAND_CLOSE_WINDOW,
#ifndef NDEBUG
    COMMAND_DEBUG_TOGGLE_WIREFRAME,
    COMMAND_DEBUG_SWITCH_KEYBOARD_TO_PLAYER1,
    COMMAND_DEBUG_SWITCH_KEYBOARD_TO_PLAYER2,
    COMMAND_DEBUG_SWITCH_KEYBOARD_TO_PLAYER3,
    COMMAND_DEBUG_SWITCH_KEYBOARD_TO_PLAYER4,
    COMMAND_DEBUG_TOGGLE_DEBUG_CAMERA,
    COMMAND_DEBUG_TOGGLE_DRAW_BOUNDING_BOXES,
    COMMAND_DEBUG_TOGGLE_DRAW_SPATIAL_MAP,
    COMMAND_DEBUG_SET_UI_DISPLAY_COUNT_0,
    COMMAND_DEBUG_SET_UI_DISPLAY_COUNT_1,
    COMMAND_DEBUG_SET_UI_DISPLAY_COUNT_2,
    COMMAND_DEBUG_SET_UI_DISPLAY_COUNT_3,
    COMMAND_DEBUG_SET_UI_DISPLAY_COUNT_4,
#endif
};
